pipeline {
    agent any
    /* agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    } */
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
               /* sh 'npm install' */
            }
        }
        stage('Test') {
            steps {
               /* sh './jenkins/scripts/test.sh' */
            }
        }
       /* stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
               sh './jenkins/scripts/kill.sh' 
            } */
         stage('Build Docker Image'){
             steps {
                 echo "Running ${env.BUILD_TAG} and Build_id is ${env.BUILD_ID}"
                /* sh 'docker build -t simple-node-app-v2 .' */
            }   
        }
    }
}
