pipeline {
    agent any
    /* agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    } */
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
               /*echo "Hello" */
               sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                 /* echo "Hello" */
               sh './jenkins/scripts/test.sh'
            }
        }
       /* stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
               sh './jenkins/scripts/kill.sh' 
            } */
         stage('Build Docker Image'){
             steps {
                 /* echo "Running ${env.BUILD_TAG} and Build_id is ${env.BUILD_ID}" */
                 sh "docker build -t simple-node-app-${env.BUILD_ID} ." 
            }
          stage('Run Docker Image'){
             steps {
                 /* echo "Running ${env.BUILD_TAG} and Build_id is ${env.BUILD_ID}" */
                 sh "docker run -dp 3000:3000 simple-node-app-${env.BUILD_ID} ." 
            }   
        }
    }
}
